//The purpose of this file is to take notes of the current game design
/*

TOWER DEFENSE:
You are a modular being created to protect all existence

all defenses can be given elements
ailments
player defense modules (similiar to factorio)



Terrain Generation:
Similar to the particle system, the terrain is generated by declaring a TerrainMaster object, which takes in the size of the desired terrain.
	The TerrainMaster class will store all information for the terrain so that it can be accessed easily later
	On construction, the terrain master will call its 'generate terrain' method, which implement- which is effectively a terrain system. 

TerrainMaster is the brain behind the entire system. Its constructor will take in the desired terrainSize
*/